### PR TITLE
Absolute value and stop/continue keyword

### PR DESCRIPTION
**Pull request by Akash-Nayar**
Changes
- Added token (lists) for `CONTINUE` and `STOP`.
- Add new `uop` type `Abs`
- Rewrite `string_of_uop` into `string_of_expr`
- Add absolute value and continue/stop rules in parser
- Updated tests

**TODO: Update semant to only allow continue/stop within loops**

### CODE REVIEW

**Comment by Akash-Nayar** [comment]
@20joshuaz how tough do you think semantics are for continue/stop?

**Comment by 20joshuaz** [comment]
> @20joshuaz how tough do you think semantics are for continue/stop?

Do you want me to check for unreachable code? Like should this compile?
```
loop some_condition:
  stop
  say("Hello")
```
Either way shouldn't be too bad.

**Comment by 20joshuaz** [comment]
just to confirm, is absolute value used for numbers and arrays (to get size)?

**Review by 20joshuaz — APPROVED** [review]
LGTM 💸

**Comment by Akash-Nayar** [comment]
> just to confirm, is absolute value used for numbers and arrays (to get size)?

@20joshuaz hmmm I forgot about its use for arrays... i guess this is easy to do for 1d arrays but if not sure what it would return for multidimensional arrays if we choose to implement those. maybe we can add functionality for 1d arrays and abs in a diff pr?

**Comment by Akash-Nayar** [comment]
> > @20joshuaz how tough do you think semantics are for continue/stop?
> 
> Do you want me to check for unreachable code? Like should this compile?
> 
> ```
> loop some_condition:
>   stop
>   say("Hello")
> ```
> 
> Either way shouldn't be too bad.

@20joshuaz as a start we don't need to check for dead code. i guess we can do that later if we have time

**Comment by Akash-Nayar** [comment]
@20joshuaz should i merge?

**Comment by 20joshuaz** [comment]
sure

**Pull request merged**
